services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=`rake secret`
    command: >
      sh -c "bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/usr/share/swagger-ui/openapi.yaml
    environment:
      - SWAGGER_JSON=/usr/share/swagger-ui/openapi.yaml
    restart: always
